qa_model:
  name: gpt-5-mini
confidence_extractor:
  name: linguistic_confidence
  model_name: distilroberta-base
  state_dict_path: llm_linguistic_confidence_study/pretrained_weights/human_anno_trained_reg_head.pth
  mapper_name: self-trained
  qa_template: vanilla
  type: human_anno_dataset_trained
dataset:
  grader_model:
    name: gpt-5-mini
  name: simple_qa
  url: https://huggingface.co/datasets/basicv8vc/SimpleQA/blob/main/simple_qa_test_set.csv
  file_path: llm_linguistic_confidence_study/datasets/simple_qa_test_set.csv
metrics:
  acc:
    _target_: metrics.Accuracy
    name: acc
    format: simpleqa_like
    exclude_not_attempted: true
  ece:
    _target_: metrics.ECE
    name: ece
    n_bins: 15
    format: simpleqa_like
    exclude_not_attempted: true
  auroc:
    _target_: metrics.AUROC
    name: auroc
    format: simpleqa_like
    exclude_not_attempted: false
pre_runned_batch:
  qa_batch_id: batch_689f470723288190a79fb84227cce093
  grader_batch_id: batch_689f4f41fe3c8190beb3763dd2c0b142
seed: 42
