qa_batch_id: llm_linguistic_confidence_study/prerunned_batch/mini_simple_qa/qwen3-8b-lora-mapper2/linguistic_confidence/vanilla-dp-qwen3-8b-lora-mapper2.csv
grader_batch_id: batch_68c0cfa4e8088190bb9c529dac7aa16f
ece_batch_id: batch_68c0c71ee7a081908dd0462042dc8933