qa_batch_id: llm_linguistic_confidence_study/prerunned_batch/simple_qa/qwen3-32b/semantic_uncertainty/vanilla-qwen3-32b.csv
grader_batch_id: null
semantic_ids_path: llm_linguistic_confidence_study/pretrained_weights/semantic_ids_qwen3-32b.npy