qa_batch_id: llm_linguistic_confidence_study/prerunned_batch/simple_qa/qwen3-8b/linguistic_confidence/vanilla-qwen3-8b.csv
grader_batch_id: batch_68bfbb745d3081909293ff856e977c27
ece_batch_id: batch_68c10d3c3638819082664e3f6f314161