qa_batch_id: llm_linguistic_confidence_study/prerunned_batch/simple_qa/qwen3-8b-lora-mapper2/linguistic_confidence/vanilla-uncertainty-qwen3-8b-lora-mapper2.csv
grader_batch_id: batch_68b99cb9b8ec819091c76a0ff9042595
ece_batch_id: batch_68c10e4c5e7481909efabc499837e844