qa_batch_id: llm_linguistic_confidence_study/prerunned_batch/simple_qa/qwen3-8b-lora-mapper0/linguistic_confidence/vanilla-uncertainty-qwen3-8b-lora-mapper0.csv
grader_batch_id: batch_68b981d8a254819098d73a9be885d740
ece_batch_id: batch_68c10d9be2708190be471ef42ed9e09c