qa_batch_id: llm_linguistic_confidence_study/prerunned_batch/simple_qa/qwen3-8b-lora-mapper3/linguistic_confidence/vanilla-uncertainty-qwen3-8b-lora-mapper3.csv
grader_batch_id: batch_68b9c5e09c8c819085a19853afece8ad
ece_batch_id: batch_68c10e7437e08190bd2d2ab80f809410